import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import Header from '@/components/header'
import Sidebar from '@/components/sidebar'

// import '@/styles/globals.css' // Import your global styles

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
      <div className="flex flex-col h-screen bg-background text-foreground">
        <Header />

        <div className="flex flex-1 overflow-hidden">
          {/* Sidebar for larger screens */}
          <aside className="hidden md:block w-64 border-r p-4">
            <Sidebar />
          </aside>

          {/* Dynamic main content */}
          <main className="flex-1 p-4 overflow-auto">
            {children}
          </main>
        </div>
      </div>
  )
}